import { Hono } from "hono";
import pdfGenerator from "../pdf/pdf-generator.js";
import { zValidator } from "@hono/zod-validator";
import z from "zod";
import { content } from "pdfkit/js/page";

const schema = z.object({
  title: z.string(),
  content: z.array(z.string()),
});

const pdfExample = new Hono();

pdfExample.post("/", zValidator("form", schema), async (c) => {
  const body = await c.req.json();

  const pdfFile = await pdfGenerator({
    filename: "example-pdf",
    content: (doc) => {
      // Title
      doc.fontSize(18).text(body.title, { align: "center" });
      doc.moveDown();

      // Write content
      body.content.forEach((text: string) => {
        doc.fontSize(12).text(text, 50);
        doc.text(text, 50);
      });
    },
  });

  return pdfFile;
});

pdfExample.get("/", async () => {
  const pdfFile = await pdfGenerator({
    filename: "example-pdf",
    content: (doc) => {
      // Title
      doc.fontSize(18).text(data.title, { align: "center" });
      doc.moveDown();

      // Write content
      data.content.forEach((text: string) => {
        doc.fontSize(12).text(text, 50);
        doc.moveDown();
      });
    },
  });
  return pdfFile;
});

export default pdfExample;

const data = {
  title: "Laporan Pembelian",
  content: [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut interdum elit. Pellentesque lorem leo, facilisis quis condimentum ac, semper sit amet neque. Aliquam ultrices gravida massa, quis molestie nunc dictum vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras a nisi vitae felis dignissim auctor. Curabitur accumsan enim et rutrum venenatis. Mauris pellentesque, ante fermentum ullamcorper vestibulum, odio ligula cursus sapien, et tincidunt turpis ipsum sed ante. Maecenas sed ornare felis, in tempus lectus. Nullam nibh felis, tempor eget rhoncus non, aliquam non lectus. Mauris sodales, ligula at tempus dictum, massa orci congue diam, facilisis interdum neque lectus et nulla. Vestibulum commodo augue ut est tincidunt suscipit. In rutrum eleifend accumsan. Aliquam ultrices dignissim metus quis porttitor. In porta molestie sapien id elementum. Duis magna elit, tincidunt vel pretium nec, aliquam vitae lectus. Suspendisse porta quis libero vitae sagittis. In accumsan massa sit amet eros rutrum pellentesque. Cras vitae tristique urna. Quisque aliquam pharetra enim, bibendum aliquam mauris. Nam sed placerat diam. Morbi eget tempus arcu. Curabitur odio sem, pharetra vel mattis sed, pellentesque in ex. Praesent pharetra velit mauris. Suspendisse porta erat in condimentum mattis. Mauris metus lectus, molestie sit amet sem ac, placerat vulputate magna. Nulla facilisi. Morbi felis odio, efficitur sit amet sapien quis, tempor sodales augue. Sed sit amet tempus felis, ut accumsan lacus. Nunc pharetra pretium libero, eget tristique massa varius sagittis. Donec gravida ornare neque vitae rhoncus. Vivamus egestas mi suscipit tortor accumsan tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras fermentum pulvinar nulla sit amet congue. Nunc laoreet rhoncus sollicitudin. Fusce dapibus risus sit amet hendrerit sollicitudin. Vestibulum sed enim magna. Vivamus at sodales nibh. In risus dolor, rhoncus sed accumsan et, sodales sit amet nibh. Pellentesque vitae justo non tellus facilisis tempor. Nulla at lobortis arcu, id malesuada massa. Morbi at faucibus metus. Morbi quis metus ac turpis imperdiet laoreet. Aliquam gravida iaculis orci, non mollis quam iaculis in. Donec et nisl iaculis, cursus tellus vel, sodales mi.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut interdum elit. Pellentesque lorem leo, facilisis quis condimentum ac, semper sit amet neque. Aliquam ultrices gravida massa, quis molestie nunc dictum vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras a nisi vitae felis dignissim auctor. Curabitur accumsan enim et rutrum venenatis. Mauris pellentesque, ante fermentum ullamcorper vestibulum, odio ligula cursus sapien, et tincidunt turpis ipsum sed ante. Maecenas sed ornare felis, in tempus lectus. Nullam nibh felis, tempor eget rhoncus non, aliquam non lectus. Mauris sodales, ligula at tempus dictum, massa orci congue diam, facilisis interdum neque lectus et nulla. Vestibulum commodo augue ut est tincidunt suscipit. In rutrum eleifend accumsan. Aliquam ultrices dignissim metus quis porttitor. In porta molestie sapien id elementum. Duis magna elit, tincidunt vel pretium nec, aliquam vitae lectus. Suspendisse porta quis libero vitae sagittis. In accumsan massa sit amet eros rutrum pellentesque. Cras vitae tristique urna. Quisque aliquam pharetra enim, bibendum aliquam mauris. Nam sed placerat diam. Morbi eget tempus arcu. Curabitur odio sem, pharetra vel mattis sed, pellentesque in ex. Praesent pharetra velit mauris. Suspendisse porta erat in condimentum mattis. Mauris metus lectus, molestie sit amet sem ac, placerat vulputate magna. Nulla facilisi. Morbi felis odio, efficitur sit amet sapien quis, tempor sodales augue. Sed sit amet tempus felis, ut accumsan lacus. Nunc pharetra pretium libero, eget tristique massa varius sagittis. Donec gravida ornare neque vitae rhoncus. Vivamus egestas mi suscipit tortor accumsan tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras fermentum pulvinar nulla sit amet congue. Nunc laoreet rhoncus sollicitudin. Fusce dapibus risus sit amet hendrerit sollicitudin. Vestibulum sed enim magna. Vivamus at sodales nibh. In risus dolor, rhoncus sed accumsan et, sodales sit amet nibh. Pellentesque vitae justo non tellus facilisis tempor. Nulla at lobortis arcu, id malesuada massa. Morbi at faucibus metus. Morbi quis metus ac turpis imperdiet laoreet. Aliquam gravida iaculis orci, non mollis quam iaculis in. Donec et nisl iaculis, cursus tellus vel, sodales mi.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut interdum elit. Pellentesque lorem leo, facilisis quis condimentum ac, semper sit amet neque. Aliquam ultrices gravida massa, quis molestie nunc dictum vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras a nisi vitae felis dignissim auctor. Curabitur accumsan enim et rutrum venenatis. Mauris pellentesque, ante fermentum ullamcorper vestibulum, odio ligula cursus sapien, et tincidunt turpis ipsum sed ante. Maecenas sed ornare felis, in tempus lectus. Nullam nibh felis, tempor eget rhoncus non, aliquam non lectus. Mauris sodales, ligula at tempus dictum, massa orci congue diam, facilisis interdum neque lectus et nulla. Vestibulum commodo augue ut est tincidunt suscipit. In rutrum eleifend accumsan. Aliquam ultrices dignissim metus quis porttitor. In porta molestie sapien id elementum. Duis magna elit, tincidunt vel pretium nec, aliquam vitae lectus. Suspendisse porta quis libero vitae sagittis. In accumsan massa sit amet eros rutrum pellentesque. Cras vitae tristique urna. Quisque aliquam pharetra enim, bibendum aliquam mauris. Nam sed placerat diam. Morbi eget tempus arcu. Curabitur odio sem, pharetra vel mattis sed, pellentesque in ex. Praesent pharetra velit mauris. Suspendisse porta erat in condimentum mattis. Mauris metus lectus, molestie sit amet sem ac, placerat vulputate magna. Nulla facilisi. Morbi felis odio, efficitur sit amet sapien quis, tempor sodales augue. Sed sit amet tempus felis, ut accumsan lacus. Nunc pharetra pretium libero, eget tristique massa varius sagittis. Donec gravida ornare neque vitae rhoncus. Vivamus egestas mi suscipit tortor accumsan tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras fermentum pulvinar nulla sit amet congue. Nunc laoreet rhoncus sollicitudin. Fusce dapibus risus sit amet hendrerit sollicitudin. Vestibulum sed enim magna. Vivamus at sodales nibh. In risus dolor, rhoncus sed accumsan et, sodales sit amet nibh. Pellentesque vitae justo non tellus facilisis tempor. Nulla at lobortis arcu, id malesuada massa. Morbi at faucibus metus. Morbi quis metus ac turpis imperdiet laoreet. Aliquam gravida iaculis orci, non mollis quam iaculis in. Donec et nisl iaculis, cursus tellus vel, sodales mi.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut interdum elit. Pellentesque lorem leo, facilisis quis condimentum ac, semper sit amet neque. Aliquam ultrices gravida massa, quis molestie nunc dictum vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras a nisi vitae felis dignissim auctor. Curabitur accumsan enim et rutrum venenatis. Mauris pellentesque, ante fermentum ullamcorper vestibulum, odio ligula cursus sapien, et tincidunt turpis ipsum sed ante. Maecenas sed ornare felis, in tempus lectus. Nullam nibh felis, tempor eget rhoncus non, aliquam non lectus. Mauris sodales, ligula at tempus dictum, massa orci congue diam, facilisis interdum neque lectus et nulla. Vestibulum commodo augue ut est tincidunt suscipit. In rutrum eleifend accumsan. Aliquam ultrices dignissim metus quis porttitor. In porta molestie sapien id elementum. Duis magna elit, tincidunt vel pretium nec, aliquam vitae lectus. Suspendisse porta quis libero vitae sagittis. In accumsan massa sit amet eros rutrum pellentesque. Cras vitae tristique urna. Quisque aliquam pharetra enim, bibendum aliquam mauris. Nam sed placerat diam. Morbi eget tempus arcu. Curabitur odio sem, pharetra vel mattis sed, pellentesque in ex. Praesent pharetra velit mauris. Suspendisse porta erat in condimentum mattis. Mauris metus lectus, molestie sit amet sem ac, placerat vulputate magna. Nulla facilisi. Morbi felis odio, efficitur sit amet sapien quis, tempor sodales augue. Sed sit amet tempus felis, ut accumsan lacus. Nunc pharetra pretium libero, eget tristique massa varius sagittis. Donec gravida ornare neque vitae rhoncus. Vivamus egestas mi suscipit tortor accumsan tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras fermentum pulvinar nulla sit amet congue. Nunc laoreet rhoncus sollicitudin. Fusce dapibus risus sit amet hendrerit sollicitudin. Vestibulum sed enim magna. Vivamus at sodales nibh. In risus dolor, rhoncus sed accumsan et, sodales sit amet nibh. Pellentesque vitae justo non tellus facilisis tempor. Nulla at lobortis arcu, id malesuada massa. Morbi at faucibus metus. Morbi quis metus ac turpis imperdiet laoreet. Aliquam gravida iaculis orci, non mollis quam iaculis in. Donec et nisl iaculis, cursus tellus vel, sodales mi.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut interdum elit. Pellentesque lorem leo, facilisis quis condimentum ac, semper sit amet neque. Aliquam ultrices gravida massa, quis molestie nunc dictum vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras a nisi vitae felis dignissim auctor. Curabitur accumsan enim et rutrum venenatis. Mauris pellentesque, ante fermentum ullamcorper vestibulum, odio ligula cursus sapien, et tincidunt turpis ipsum sed ante. Maecenas sed ornare felis, in tempus lectus. Nullam nibh felis, tempor eget rhoncus non, aliquam non lectus. Mauris sodales, ligula at tempus dictum, massa orci congue diam, facilisis interdum neque lectus et nulla. Vestibulum commodo augue ut est tincidunt suscipit. In rutrum eleifend accumsan. Aliquam ultrices dignissim metus quis porttitor. In porta molestie sapien id elementum. Duis magna elit, tincidunt vel pretium nec, aliquam vitae lectus. Suspendisse porta quis libero vitae sagittis. In accumsan massa sit amet eros rutrum pellentesque. Cras vitae tristique urna. Quisque aliquam pharetra enim, bibendum aliquam mauris. Nam sed placerat diam. Morbi eget tempus arcu. Curabitur odio sem, pharetra vel mattis sed, pellentesque in ex. Praesent pharetra velit mauris. Suspendisse porta erat in condimentum mattis. Mauris metus lectus, molestie sit amet sem ac, placerat vulputate magna. Nulla facilisi. Morbi felis odio, efficitur sit amet sapien quis, tempor sodales augue. Sed sit amet tempus felis, ut accumsan lacus. Nunc pharetra pretium libero, eget tristique massa varius sagittis. Donec gravida ornare neque vitae rhoncus. Vivamus egestas mi suscipit tortor accumsan tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras fermentum pulvinar nulla sit amet congue. Nunc laoreet rhoncus sollicitudin. Fusce dapibus risus sit amet hendrerit sollicitudin. Vestibulum sed enim magna. Vivamus at sodales nibh. In risus dolor, rhoncus sed accumsan et, sodales sit amet nibh. Pellentesque vitae justo non tellus facilisis tempor. Nulla at lobortis arcu, id malesuada massa. Morbi at faucibus metus. Morbi quis metus ac turpis imperdiet laoreet. Aliquam gravida iaculis orci, non mollis quam iaculis in. Donec et nisl iaculis, cursus tellus vel, sodales mi.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut interdum elit. Pellentesque lorem leo, facilisis quis condimentum ac, semper sit amet neque. Aliquam ultrices gravida massa, quis molestie nunc dictum vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras a nisi vitae felis dignissim auctor. Curabitur accumsan enim et rutrum venenatis. Mauris pellentesque, ante fermentum ullamcorper vestibulum, odio ligula cursus sapien, et tincidunt turpis ipsum sed ante. Maecenas sed ornare felis, in tempus lectus. Nullam nibh felis, tempor eget rhoncus non, aliquam non lectus. Mauris sodales, ligula at tempus dictum, massa orci congue diam, facilisis interdum neque lectus et nulla. Vestibulum commodo augue ut est tincidunt suscipit. In rutrum eleifend accumsan. Aliquam ultrices dignissim metus quis porttitor. In porta molestie sapien id elementum. Duis magna elit, tincidunt vel pretium nec, aliquam vitae lectus. Suspendisse porta quis libero vitae sagittis. In accumsan massa sit amet eros rutrum pellentesque. Cras vitae tristique urna. Quisque aliquam pharetra enim, bibendum aliquam mauris. Nam sed placerat diam. Morbi eget tempus arcu. Curabitur odio sem, pharetra vel mattis sed, pellentesque in ex. Praesent pharetra velit mauris. Suspendisse porta erat in condimentum mattis. Mauris metus lectus, molestie sit amet sem ac, placerat vulputate magna. Nulla facilisi. Morbi felis odio, efficitur sit amet sapien quis, tempor sodales augue. Sed sit amet tempus felis, ut accumsan lacus. Nunc pharetra pretium libero, eget tristique massa varius sagittis. Donec gravida ornare neque vitae rhoncus. Vivamus egestas mi suscipit tortor accumsan tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras fermentum pulvinar nulla sit amet congue. Nunc laoreet rhoncus sollicitudin. Fusce dapibus risus sit amet hendrerit sollicitudin. Vestibulum sed enim magna. Vivamus at sodales nibh. In risus dolor, rhoncus sed accumsan et, sodales sit amet nibh. Pellentesque vitae justo non tellus facilisis tempor. Nulla at lobortis arcu, id malesuada massa. Morbi at faucibus metus. Morbi quis metus ac turpis imperdiet laoreet. Aliquam gravida iaculis orci, non mollis quam iaculis in. Donec et nisl iaculis, cursus tellus vel, sodales mi.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut interdum elit. Pellentesque lorem leo, facilisis quis condimentum ac, semper sit amet neque. Aliquam ultrices gravida massa, quis molestie nunc dictum vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras a nisi vitae felis dignissim auctor. Curabitur accumsan enim et rutrum venenatis. Mauris pellentesque, ante fermentum ullamcorper vestibulum, odio ligula cursus sapien, et tincidunt turpis ipsum sed ante. Maecenas sed ornare felis, in tempus lectus. Nullam nibh felis, tempor eget rhoncus non, aliquam non lectus. Mauris sodales, ligula at tempus dictum, massa orci congue diam, facilisis interdum neque lectus et nulla. Vestibulum commodo augue ut est tincidunt suscipit. In rutrum eleifend accumsan. Aliquam ultrices dignissim metus quis porttitor. In porta molestie sapien id elementum. Duis magna elit, tincidunt vel pretium nec, aliquam vitae lectus. Suspendisse porta quis libero vitae sagittis. In accumsan massa sit amet eros rutrum pellentesque. Cras vitae tristique urna. Quisque aliquam pharetra enim, bibendum aliquam mauris. Nam sed placerat diam. Morbi eget tempus arcu. Curabitur odio sem, pharetra vel mattis sed, pellentesque in ex. Praesent pharetra velit mauris. Suspendisse porta erat in condimentum mattis. Mauris metus lectus, molestie sit amet sem ac, placerat vulputate magna. Nulla facilisi. Morbi felis odio, efficitur sit amet sapien quis, tempor sodales augue. Sed sit amet tempus felis, ut accumsan lacus. Nunc pharetra pretium libero, eget tristique massa varius sagittis. Donec gravida ornare neque vitae rhoncus. Vivamus egestas mi suscipit tortor accumsan tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras fermentum pulvinar nulla sit amet congue. Nunc laoreet rhoncus sollicitudin. Fusce dapibus risus sit amet hendrerit sollicitudin. Vestibulum sed enim magna. Vivamus at sodales nibh. In risus dolor, rhoncus sed accumsan et, sodales sit amet nibh. Pellentesque vitae justo non tellus facilisis tempor. Nulla at lobortis arcu, id malesuada massa. Morbi at faucibus metus. Morbi quis metus ac turpis imperdiet laoreet. Aliquam gravida iaculis orci, non mollis quam iaculis in. Donec et nisl iaculis, cursus tellus vel, sodales mi.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut interdum elit. Pellentesque lorem leo, facilisis quis condimentum ac, semper sit amet neque. Aliquam ultrices gravida massa, quis molestie nunc dictum vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras a nisi vitae felis dignissim auctor. Curabitur accumsan enim et rutrum venenatis. Mauris pellentesque, ante fermentum ullamcorper vestibulum, odio ligula cursus sapien, et tincidunt turpis ipsum sed ante. Maecenas sed ornare felis, in tempus lectus. Nullam nibh felis, tempor eget rhoncus non, aliquam non lectus. Mauris sodales, ligula at tempus dictum, massa orci congue diam, facilisis interdum neque lectus et nulla. Vestibulum commodo augue ut est tincidunt suscipit. In rutrum eleifend accumsan. Aliquam ultrices dignissim metus quis porttitor. In porta molestie sapien id elementum. Duis magna elit, tincidunt vel pretium nec, aliquam vitae lectus. Suspendisse porta quis libero vitae sagittis. In accumsan massa sit amet eros rutrum pellentesque. Cras vitae tristique urna. Quisque aliquam pharetra enim, bibendum aliquam mauris. Nam sed placerat diam. Morbi eget tempus arcu. Curabitur odio sem, pharetra vel mattis sed, pellentesque in ex. Praesent pharetra velit mauris. Suspendisse porta erat in condimentum mattis. Mauris metus lectus, molestie sit amet sem ac, placerat vulputate magna. Nulla facilisi. Morbi felis odio, efficitur sit amet sapien quis, tempor sodales augue. Sed sit amet tempus felis, ut accumsan lacus. Nunc pharetra pretium libero, eget tristique massa varius sagittis. Donec gravida ornare neque vitae rhoncus. Vivamus egestas mi suscipit tortor accumsan tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras fermentum pulvinar nulla sit amet congue. Nunc laoreet rhoncus sollicitudin. Fusce dapibus risus sit amet hendrerit sollicitudin. Vestibulum sed enim magna. Vivamus at sodales nibh. In risus dolor, rhoncus sed accumsan et, sodales sit amet nibh. Pellentesque vitae justo non tellus facilisis tempor. Nulla at lobortis arcu, id malesuada massa. Morbi at faucibus metus. Morbi quis metus ac turpis imperdiet laoreet. Aliquam gravida iaculis orci, non mollis quam iaculis in. Donec et nisl iaculis, cursus tellus vel, sodales mi.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut interdum elit. Pellentesque lorem leo, facilisis quis condimentum ac, semper sit amet neque. Aliquam ultrices gravida massa, quis molestie nunc dictum vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras a nisi vitae felis dignissim auctor. Curabitur accumsan enim et rutrum venenatis. Mauris pellentesque, ante fermentum ullamcorper vestibulum, odio ligula cursus sapien, et tincidunt turpis ipsum sed ante. Maecenas sed ornare felis, in tempus lectus. Nullam nibh felis, tempor eget rhoncus non, aliquam non lectus. Mauris sodales, ligula at tempus dictum, massa orci congue diam, facilisis interdum neque lectus et nulla. Vestibulum commodo augue ut est tincidunt suscipit. In rutrum eleifend accumsan. Aliquam ultrices dignissim metus quis porttitor. In porta molestie sapien id elementum. Duis magna elit, tincidunt vel pretium nec, aliquam vitae lectus. Suspendisse porta quis libero vitae sagittis. In accumsan massa sit amet eros rutrum pellentesque. Cras vitae tristique urna. Quisque aliquam pharetra enim, bibendum aliquam mauris. Nam sed placerat diam. Morbi eget tempus arcu. Curabitur odio sem, pharetra vel mattis sed, pellentesque in ex. Praesent pharetra velit mauris. Suspendisse porta erat in condimentum mattis. Mauris metus lectus, molestie sit amet sem ac, placerat vulputate magna. Nulla facilisi. Morbi felis odio, efficitur sit amet sapien quis, tempor sodales augue. Sed sit amet tempus felis, ut accumsan lacus. Nunc pharetra pretium libero, eget tristique massa varius sagittis. Donec gravida ornare neque vitae rhoncus. Vivamus egestas mi suscipit tortor accumsan tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras fermentum pulvinar nulla sit amet congue. Nunc laoreet rhoncus sollicitudin. Fusce dapibus risus sit amet hendrerit sollicitudin. Vestibulum sed enim magna. Vivamus at sodales nibh. In risus dolor, rhoncus sed accumsan et, sodales sit amet nibh. Pellentesque vitae justo non tellus facilisis tempor. Nulla at lobortis arcu, id malesuada massa. Morbi at faucibus metus. Morbi quis metus ac turpis imperdiet laoreet. Aliquam gravida iaculis orci, non mollis quam iaculis in. Donec et nisl iaculis, cursus tellus vel, sodales mi.",
  ],
};
